### PR TITLE
add preview releases

### PR DESCRIPTION
**Pull request by AdrianGonz97**

### CODE REVIEW

**Review by AdrianGonz97 — COMMENTED** [review]
submitting a review...

**Review by AdrianGonz97 — COMMENTED** [review]
...

**Comment by Aslemammad** [comment]
Hey team! I hope you're doing well.

I see you closed this issue, I'd like to see the reason and how can I help to get it merged 😄

Thank you all!

**Comment by AdrianGonz97** [comment]
hey @Aslemammad!

this is my personal fork of `svelte-add` where I was experimenting with it before adding it to the main repo here: https://github.com/svelte-add/svelte-add/issues/383

we're absolutely loving it!! thank you so much for all your work on it, it's amazing!

**Comment by Aslemammad** [comment]
Thank you so much for the kind words, I'm really excited ❤️

**Pull request closed without merging**
